export const mockCurrentGameSessions = [
  {
    id: 1,
    startTime: "14:00:00",
    endTime: "16:00:00",
    locationName: "Location 1",
    locationAddress: "Location 1 Address",
    memberCapacity: 40,
    casualCapacity: 5,
    memberBookingCount: 5,
    casualBookingCount: 3,
  },
  {
    id: 2,
    startTime: "14:00:00",
    endTime: "16:00:00",
    locationName: "Location 2",
    locationAddress: "Location 2 Address",
    memberCapacity: 40,
    casualCapacity: 5,
    memberBookingCount: 5,
    casualBookingCount: 3,
  },
  {
    id: 3,
    startTime: "14:00:00",
    endTime: "16:00:00",
    locationName: "Location 3",
    locationAddress: "Location 3 Address",
    memberCapacity: 40,
    casualCapacity: 5,
    memberBookingCount: 5,
    casualBookingCount: 3,
  },
  {
    id: 4,
    startTime: "14:00:00",
    endTime: "16:00:00",
    locationName: "Location 4",
    locationAddress: "Location 4 Address",
    memberCapacity: 40,
    casualCapacity: 5,
    memberBookingCount: 40,
    casualBookingCount: 5,
  },
];
