export const mockCurrentGameSessions = [
  {
    id: 1,
    startTime: "2:00PM",
    endTime: "4:00PM",
    locationName: "Location 1",
    locationAddress: "Location 1 Address",
    capacity: 10,
    casualCapacity: 5,
    bookingCount: 5,
    casualBookingCount: 3,
  },
  {
    id: 2,
    startTime: "2:00PM",
    endTime: "4:00PM",
    locationName: "Location 2",
    locationAddress: "Location 2 Address",
    capacity: 10,
    casualCapacity: 5,
    bookingCount: 5,
    casualBookingCount: 3,
  },
  {
    id: 3,
    startTime: "2:00PM",
    endTime: "4:00PM",
    locationName: "Location 3",
    locationAddress: "Location 3 Address",
    capacity: 10,
    casualCapacity: 5,
    bookingCount: 5,
    casualBookingCount: 3,
  },
  {
    id: 4,
    startTime: "2:00PM",
    endTime: "4:00PM",
    locationName: "Location 4",
    locationAddress: "Location 4 Address",
    capacity: 10,
    casualCapacity: 5,
    bookingCount: 10,
    casualBookingCount: 3,
  },
];
