# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'wdcc-uabc'
primary_region = 'syd'

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 3000
  force_https = true  
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

[[services]]
internal_port = 5432 # Postgres instance
protocol = "tcp"