app = "wdcc-uabc"
primary_region = "syd"
# fly.toml app configuration file generated for wdcc-mem on 2023-09-28T21:53:38+13:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#
[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
