name: Build Test

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"
          
      - name: yarn install
        run: |
          yarn install

      - name: server build and test
        run: |
          yarn workspace server build

      - name: client build and test
        run: |
          yarn workspace client build
