name: Build Test

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        name: Setup pnpm
        with:
          version: 8

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Create env file
        run: echo ${{ secrets.UABC_DEV_BACKEND_ENVFILE }} | base64 --decode > .env

      - name: Build Next app
        run: |
          pnpm build
