name: Build Test

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"

      - name: yarn install
        run: |
          yarn install


      - name: prisma generate
        run: |
          npx prisma generate

      - name: Build Next app
        run: |
          yarn build
