name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    name: Deploy Staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Fly Deploy
        working-directory: ./
        run: flyctl deploy --remote-only --config fly.staging.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_WEB_STAGING_API_TOKEN }}
