name: Deploy Staging
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  FLY_API_TOKEN: ${{ secrets.FLY_WEB_STAGING_API_TOKEN }}

jobs:
  deploy:
    name: Deploy app
    environment: development
    runs-on: ubuntu-latest
    concurrency: deploy-group # optional: ensure only one action runs at a time
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Check node version
        run: |
          node -v

      - name: Use Latest Corepack
        run: |
          echo "Before: corepack version => $(corepack --version || echo 'not installed')"
          npm install -g corepack@latest
          echo "After : corepack version => $(corepack --version)"
          corepack enable
          pnpm --version

      - name: Deploy
        run: |
          flyctl deploy --remote-only --config fly.staging.toml \
          --build-arg APP_URL="${{ secrets.APP_URL }}" \
          --build-secret DATABASE_URL="${{ secrets.DATABASE_URL }}" \
          --build-secret NEXTAUTH_SECRET="${{ secrets.NEXTAUTH_SECRET }}"
