name: Deploy to Production

on: [workflow_dispatch]

jobs:
  deploy-frontend:
    name: Deploy Frontend Prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Fly Deploy
        working-directory: ./frontend
        run: flyctl deploy --remote-only --config fly.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_WEB_PRODUCTION_API_TOKEN }}
