name: Build Test

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: development
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          run_install: true

      - name: prisma generate
        run: |
          npx prisma generate

      - name: Create env file
        run: echo ${{ secrets.UABC_DEV_BACKEND_ENVFILE }} | base64 --decode > .env

      - name: Build Next app
        run: |
          pnpm build

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.UABC_DEV_GCP_DEPLOYMENT_SA_CREDENTIALS }}"

      - id: "app-engine-deploy"
        uses: "google-github-actions/deploy-appengine@v2"
        with:
          project_id: wdcc-uabc-dev
          working_directory: ./
