name: E2E Playwright Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches: [main]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        name: Setup pnpm
        with:
          version: 8

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - name: Create env file
        run: echo ${{ secrets.UABC_DEV_BACKEND_ENVFILE }} | base64 --decode > .env

      - name: Build Next app
        env:
          CI: true
        run: |
          pnpm build

      - name: Run Playwright tests
        run: pnpm test:e2e

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
